## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
cache:
  pip: true
  directories:
    - /home/travis/.julia

matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
before_script:
  - julia -e 'Pkg.update()'
  # Install Coverage.jl and Documenter.jl here so that they will be cached:
  - julia -e 'map(Pkg.add, ["Coverage", "Documenter"])'

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LyapunovExponents"); Pkg.test("LyapunovExponents"; coverage=true)'
before_cache:
  - julia -e 'Pkg.rm("LyapunovExponents")'
  - ls ~/.julia/v*/
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); include(joinpath("docs", "make.jl"))'
