## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
env:
  - REQUIRE_VERSIONS=minimal
  - REQUIRE_VERSIONS=latest
notifications:
  email: false
git:
  depth: 99999999
cache:
  pip: true
  directories:
    - /home/travis/.julia

matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
before_script:
  # Remove this package to install it afresh (by the default script).
  # Note that we cannot use `before_cache` to remove it before the
  # cache upload since it occurs before `after_success` in which
  # Documenter.jl needs it:
  - julia -e 'Pkg.rm("LyapunovExponents")'
  # Install Coverage.jl and Documenter.jl here so that they will be cached:
  - julia -e 'map(Pkg.add, ["Coverage", "Documenter", "GR"])'
  # Run misc/use-minimal-versions.jl or misc/use-latest-versions.jl to
  # install appropriate packages:
  - julia misc/use-"$REQUIRE_VERSIONS"-versions.jl

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LyapunovExponents"); Pkg.test("LyapunovExponents"; coverage=true)'
after_success:
  - julia misc/show-versions.jl
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("LyapunovExponents")); include(joinpath("docs", "make.jl"))'
